### PR TITLE
impl Display for Biscuit

### PR DESCRIPTION
**Pull request by BastienVigneron**

### CODE REVIEW

**Comment by BastienVigneron** [comment]
Please not a strange behavior on CI, that fail on  `token::authorizer::tests::authorizer_with_scopes` test : 

```
thread 'token::authorizer::tests::authorizer_with_scopes' panicked at 'called `Result::unwrap()` on an `Err` value: RunLimit(Timeout)', biscuit-auth/src/token/authorizer.rs:1443:13
[273](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405424475/jobs/5663384840#step:5:274)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[274](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405424475/jobs/5663384840#step:5:275)

[275](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405424475/jobs/5663384840#step:5:276)

[276](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405424475/jobs/5663384840#step:5:277)
failures:
[277](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405424475/jobs/5663384840#step:5:278)
    token::authorizer::tests::authorizer_with_scopes
[278](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405424475/jobs/5663384840#step:5:279)

[279](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405424475/jobs/5663384840#step:5:280)
test result: FAILED. 43 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.06s
[280](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405424475/jobs/5663384840#step:5:281)

[281](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405424475/jobs/5663384840#step:5:282)
Error: Process completed with exit code 101.
```

But the test pass without any issue on my laptop (with `cargo test --features serde-error --verbose`).

Any idea ?

**Comment by divarvel** [comment]
It hits a timeout because GHA runners are a bit underpowered. Running the job again usually clears the issue

**Comment by BastienVigneron** [comment]
The so know, "run it again" :)
I'll try it.

**Comment by divarvel** [comment]
Could you remove the formatting changes in the protobuf mapping types? Apart from that, LGTM.

I don't remember whether the codebase is supposed to be rustfmt'd or not, but in any case that would belong in a separate PR.

**Comment by BastienVigneron** [comment]
> I don't remember whether the codebase is supposed to be rustfmt'd or not
Obviously not, but your right this should be fixed in a separate PR.

>Could you remove the formatting changes in the protobuf mapping types?
done for `biscuit-auth/src/format/schema.rs` for I still get an error on `diff --git a/biscuit-auth/samples/README.md b/biscuit-auth/samples/README.md` : 

```
diff --git a/biscuit-auth/samples/README.md b/biscuit-auth/samples/README.md
[70](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:71)
index b959581..4f798f4 100644
[71](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:72)
--- a/biscuit-auth/samples/README.md
[72](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:73)
+++ b/biscuit-auth/samples/README.md
[73](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:74)
@@ -1339,3 +1339,80 @@ World {
[74](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:75)
 
[75](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:76)
 result: `Ok(0)`
[76](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:77)
 
[77](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:78)
+
[78](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:79)
+------------------------------
[79](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:80)
+
[80](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:81)
+## block rules: test25_check_all.bc
[81](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:82)
+### token
[82](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:83)
+
[83](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:84)
+authority:
[84](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:85)
+symbols: ["allowed_operations", "A", "B", "op", "allowed"]
[85](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:86)
+
[86](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:87)
+public keys: []
[87](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:88)
+
[88](https://github.com/BastienVigneron/biscuit-rust/actions/runs/3405840418/jobs/5664107955#step:6:89)
+```
... 
```


P.S. I've increased the timeout for `token::authorizer::tests::authorizer_with_scopes` to 5 ms.

**Comment by BastienVigneron** [comment]
Fixed (https://github.com/BastienVigneron/biscuit-rust/actions/runs/3418803724) you can approve / merge when you want.

**Comment by divarvel** [comment]
thanks!

**Pull request merged**
