### PR TITLE
biscuit-auth 4.1.0

### PR DESCRIPTION
**Pull request by Geal**

### CODE REVIEW

**Review by divarvel — COMMENTED** [review]
Looks good, could you update the changelog as well?

I assume Cargo.lock is not versionned

**Comment by Geal** [comment]
yes, it's not versioned, as it is just a set of libraries

**Review by divarvel — APPROVED** [review]

**Comment by divarvel** [comment]
> yes, it's not versioned, as it is just a set of libraries

Recommendations for cargo.lock versioning have changed recently-ish, and now putting it under version control is advised (but not required)

**Comment by Geal** [comment]
ah, I'll look into that then

**Pull request merged**
